spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.117/sell?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://192.168.1.103/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
      default-property-inclusion: non_null
server:
  context-path: /sell