spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.115/sell?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://192.168.1.101/sell?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://172.26.88.14/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
      default-property-inclusion: non_null
  redis:
    host: 192.168.0.115
    port: 6379
server:
  context-path: /sell
wechat:
  mpAppId: wx2916527695e31493
  mpAppSecret: 2b915f13b45590d64f2c89eeea521980
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  #需要配置内网穿透异步通知地址，异步通知用于微信端支付成功后访问地址，会传递一些结果给程序，程序可以根据结果考虑是否修改支付的订单状态
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
projectUrl:
  wechatMpAuthorize: http://yk2xsj.natappfree.cc
  wechatOpenAuthorize: http://yk2xsj.natappfree.cc
  sell: http://yk2xsj.natappfree.cc